### ISSUE TITLE
PAN4FUN is live

### ISSUE THREAD

**Issue by rbenamin** [pantos-io/testnet-token-list#7]
MyToken deployed at: 0xb2b58feF1E8D3422BFdF3E1C8EcE2a89B464D2FD für BNB testnetz

**Comment by jacekv** [comment]
Please fork the repository, update the README with the address, and create a PR :)

**Comment by rbenamin** [comment]
oh sorry, kind of new in github :-), i hope i done it the right way now
README is edited, PR is done! thx again! closed
